# 以下はコマンドラインで渡す
# [unstable]
# build-std = ["core", "compiler_builtins"]

# [build]
# target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
# linker = "aarch64-linux-gnu-ld"

[alias]
xbuild = "xtask build"
xrun = "xtask run"
xtest = "xtask test"
xtask = "run --package xtask --"