[workspace]
members = [
    "bootloader",
    "dtb",
    #"alloc"
]
workspace.resolver = "3"
build-std-features = ["compiler-builtins-mem"]

[profile.release]
panic = 'abort'
[profile.dev]
panic = 'abort'
