/// ペリフェラルブロックを識別するためのenum
#[derive(Debug, PartialEq, Eq, Copy, Clone)]
#[allow(clippy::upper_case_acronyms)] // 一部のブロック名がアクロニムのように見えるため許可
pub enum Rp1Block {
    Sysinfo,
    Syscfg,
    Otp,
    Power,
    Resets,
    ClocksMain,
    ClocksVideo,
    PllSys,
    PllAudio,
    PllVideo,
    Uart0,
    Uart1,
    Uart2,
    Uart3,
    Uart4,
    Uart5,
    Spi8,
    Spi0,
    Spi1,
    Spi2,
    Spi3,
    Spi4,
    Spi5,
    Spi6,
    Spi7,
    I2c0,
    I2c1,
    I2c2,
    I2c3,
    I2c4,
    I2c5,
    I2c6,
    AudioIn,
    AudioOut,
    Pwm0,
    Pwm1,
    I2s0,
    I2s1,
    I2s2,
    Timer,
    Sdio0Cfg,
    Sdio1Cfg,
    BusfabricMonitor,
    BusfabricAxishim,
    Adc,
    IoBank0,
    IoBank1,
    IoBank2,
    SysRio0,
    SysRio1,
    SysRio2,
    PadsBank0,
    PadsBank1,
    PadsBank2,
    PadsEth,
    Eth,
    EthCfg,
    Pcie,
    Mipi0Csidma,
    Mipi0Csihost,
    Mipi0Dsidma,
    Mipi0Dsihost,
    Mipi0Cfg,
    Mipi0Isp,
    Mipi1Csidma,
    Mipi1Csihost,
    Mipi1Dsidma,
    Mipi1Dsihost,
    Mipi1Cfg,
    Mipi1Isp,
    VideoOutCfg,
    VideoOutVec,
    VideoOutDpi,
    Xosc,
    Watchdog,
    DmaTick,
    Usbhost0Cfg,
    Usbhost1Cfg,
    Rosc0,
    Rosc1,
    Vbusctrl,
    Ticks,
    Pio,
    Sdio0,
    Sdio1,
    Dma,
    Usbhost0,
    Usbhost1,
    Exac,
}

#[derive(Debug, PartialEq, Eq, Copy, Clone)]
pub enum BusType {
    APB,  // Advanced Peripheral Bus
    AHB,  // Advanced High-performance Bus
    AXI3, // Advanced eXtensible Interface
}

pub struct Rp1PeripheralInfo {
    pub bus_type: BusType,
    pub atomic_access: bool,
    pub address: u32,
}

pub const fn get_block_address(block: Rp1Block) -> Rp1PeripheralInfo {
    match block {
        Rp1Block::Sysinfo => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4000_0000,
        },
        Rp1Block::Syscfg => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4000_8000,
        },
        Rp1Block::Otp => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4000_c000,
        },
        Rp1Block::Power => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4001_0000,
        },
        Rp1Block::Resets => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4001_4000,
        },
        Rp1Block::ClocksMain => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4001_8000,
        },
        Rp1Block::ClocksVideo => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4001_c000,
        },
        Rp1Block::PllSys => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4002_0000,
        },
        Rp1Block::PllAudio => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4002_4000,
        },
        Rp1Block::PllVideo => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4002_8000,
        },
        Rp1Block::Uart0 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4003_0000,
        },
        Rp1Block::Uart1 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4003_4000,
        },
        Rp1Block::Uart2 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4003_8000,
        },
        Rp1Block::Uart3 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4003_c000,
        },
        Rp1Block::Uart4 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4004_0000,
        },
        Rp1Block::Uart5 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4004_4000,
        },
        Rp1Block::Spi8 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4004_c000,
        },
        Rp1Block::Spi0 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4005_0000,
        },
        Rp1Block::Spi1 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4005_4000,
        },
        Rp1Block::Spi2 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4005_8000,
        },
        Rp1Block::Spi3 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4005_c000,
        },
        Rp1Block::Spi4 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4006_0000,
        },
        Rp1Block::Spi5 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4006_4000,
        },
        Rp1Block::Spi6 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4006_8000,
        },
        Rp1Block::Spi7 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4006_c000,
        },
        Rp1Block::I2c0 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4007_0000,
        },
        Rp1Block::I2c1 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4007_4000,
        },
        Rp1Block::I2c2 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4007_8000,
        },
        Rp1Block::I2c3 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4007_c000,
        },
        Rp1Block::I2c4 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4008_0000,
        },
        Rp1Block::I2c5 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4008_4000,
        },
        Rp1Block::I2c6 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4008_8000,
        },
        Rp1Block::AudioIn => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4009_0000,
        },
        Rp1Block::AudioOut => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4009_4000,
        },
        Rp1Block::Pwm0 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4009_8000,
        },
        Rp1Block::Pwm1 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4009_c000,
        },
        Rp1Block::I2s0 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x400a_0000,
        },
        Rp1Block::I2s1 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x400a_4000,
        },
        Rp1Block::I2s2 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x400a_8000,
        },
        Rp1Block::Timer => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400a_c000,
        },
        Rp1Block::Sdio0Cfg => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400b_0000,
        },
        Rp1Block::Sdio1Cfg => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400b_4000,
        },
        Rp1Block::BusfabricMonitor => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400c_0000,
        },
        Rp1Block::BusfabricAxishim => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400c_4000,
        },
        Rp1Block::Adc => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400c_8000,
        },
        Rp1Block::IoBank0 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400d_0000,
        },
        Rp1Block::IoBank1 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400d_4000,
        },
        Rp1Block::IoBank2 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400d_8000,
        },
        Rp1Block::SysRio0 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400e_0000,
        },
        Rp1Block::SysRio1 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400e_4000,
        },
        Rp1Block::SysRio2 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400e_8000,
        },
        Rp1Block::PadsBank0 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400f_0000,
        },
        Rp1Block::PadsBank1 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400f_4000,
        },
        Rp1Block::PadsBank2 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400f_8000,
        },
        Rp1Block::PadsEth => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x400f_c000,
        },
        Rp1Block::Eth => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4010_0000,
        },
        Rp1Block::EthCfg => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4010_4000,
        },
        Rp1Block::Pcie => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4010_8000,
        },
        Rp1Block::Mipi0Csidma => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4011_0000,
        },
        Rp1Block::Mipi0Csihost => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4011_4000,
        },
        Rp1Block::Mipi0Dsidma => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4011_8000,
        },
        Rp1Block::Mipi0Dsihost => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4011_c000,
        },
        Rp1Block::Mipi0Cfg => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4012_0000,
        },
        Rp1Block::Mipi0Isp => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4012_4000,
        },
        Rp1Block::Mipi1Csidma => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4012_8000,
        },
        Rp1Block::Mipi1Csihost => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4012_c000,
        },
        Rp1Block::Mipi1Dsidma => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4013_0000,
        },
        Rp1Block::Mipi1Dsihost => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4013_4000,
        },
        Rp1Block::Mipi1Cfg => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4013_8000,
        },
        Rp1Block::Mipi1Isp => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: false,
            address: 0x4013_c000,
        },
        Rp1Block::VideoOutCfg => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4014_0000,
        },
        Rp1Block::VideoOutVec => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4014_4000,
        },
        Rp1Block::VideoOutDpi => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4014_8000,
        },
        Rp1Block::Xosc => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4015_0000,
        },
        Rp1Block::Watchdog => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4015_4000,
        },
        Rp1Block::DmaTick => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4015_8000,
        },
        Rp1Block::Usbhost0Cfg => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4016_0000,
        },
        Rp1Block::Usbhost1Cfg => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4016_4000,
        },
        Rp1Block::Rosc0 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4016_8000,
        },
        Rp1Block::Rosc1 => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4016_c000,
        },
        Rp1Block::Vbusctrl => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4017_0000,
        },
        Rp1Block::Ticks => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4017_4000,
        },
        Rp1Block::Pio => Rp1PeripheralInfo {
            bus_type: BusType::APB,
            atomic_access: true,
            address: 0x4017_8000,
        },
        Rp1Block::Sdio0 => Rp1PeripheralInfo {
            bus_type: BusType::AHB,
            atomic_access: false,
            address: 0x4018_0000,
        },
        Rp1Block::Sdio1 => Rp1PeripheralInfo {
            bus_type: BusType::AHB,
            atomic_access: false,
            address: 0x4018_4000,
        },
        Rp1Block::Dma => Rp1PeripheralInfo {
            bus_type: BusType::AHB,
            atomic_access: false,
            address: 0x4018_8000,
        },
        Rp1Block::Usbhost0 => Rp1PeripheralInfo {
            bus_type: BusType::AXI3,
            atomic_access: false,
            address: 0x4020_0000,
        },
        Rp1Block::Usbhost1 => Rp1PeripheralInfo {
            bus_type: BusType::AXI3,
            atomic_access: false,
            address: 0x4030_0000,
        },
        Rp1Block::Exac => Rp1PeripheralInfo {
            bus_type: BusType::AXI3,
            atomic_access: false,
            address: 0x4040_0000,
        },
    }
}
